apiVersion: v1
kind: ConfigMap
metadata:
  name: whereami-grpc
data:
  BACKEND_ENABLED: "True" # assuming you don't want a chain of backend calls
  METADATA:        "frontend"
  GRPC_ENABLED: "True"
  BACKEND_SERVICE: "xds:///whereami-grpc-backend.backend.svc.cluster.local:9090"